name       : skanlite
version    : 21.12.3
release    : 11
source     :
    - https://cdn.download.kde.org/stable/release-service/21.12.3/src/skanlite-21.12.3.tar.xz : 77e09cee9f57e8bda4905d358ecf296528df8ad73c93f722c6ec689d65abbc19
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : Image Scanning Application for KDE
description: |
    Skanlite is a simple image scanning application that does nothing more than scan and save images, based on the KSane backend.
builddeps  :
    - pkgconfig(Qt5Script)
    - kdoctools-devel
    - kio-devel
    - libksane-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/doc
