name       : skanlite
version    : 2.1.0.1
release    : 2
source     :
    - https://cdn.download.kde.org/stable/skanlite/2.1/skanlite-2.1.0.1.tar.xz : b4733e55b706eaf749522aa81ec47bfd65a95c2fec994c1c47e0c4b628e70442
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : Image Scanning Application for KDE
description: |
    Skanlite is a simple image scanning application that does nothing more than scan and save images, based on the KSane backend.
builddeps  :
    - pkgconfig(libpng)
    - pkgconfig(Qt5Script)
    - extra-cmake-modules
    - kcoreaddons-devel
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - kxmlgui-devel
    - libksane-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
