name       : skanlite
version    : 22.04.2
release    : 14
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.2/src/skanlite-22.04.2.tar.xz : 2821939ec40da5dce9526408fcea6906446d60023e4329a8fd280f4054fc72cd
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : Image Scanning Application for KDE
description: |
    Skanlite is a simple image scanning application that does nothing more than scan and save images, based on the KSane backend.
builddeps  :
    - pkgconfig(Qt5Script)
    - kdoctools-devel
    - kio-devel
    - libksane-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/doc
