name       : skanlite
version    : 23.04.2
release    : 20
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.2/src/skanlite-23.04.2.tar.xz : 7474e087f21f79efc9e7ba1ca6842f096572e318b1f748fc0d752238acc6caa1
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : Image Scanning Application for KDE
description: |
    Skanlite is a simple image scanning application that does nothing more than scan and save images, based on the KSane backend.
builddeps  :
    - pkgconfig(Qt5Script)
    - kdoctools-devel
    - kio-devel
    - ksanecore-devel
    - libksane-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/doc
