name       : skanlite
version    : 2.2.0
release    : 4
source     :
    - https://cdn.download.kde.org/stable/skanlite/2.2/skanlite-2.2.0.tar.xz : 54fecc3997547bae17215af7af468a225d483ddb37be3053673392dcddd584e4
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : Image Scanning Application for KDE
description: |
    Skanlite is a simple image scanning application that does nothing more than scan and save images, based on the KSane backend.
builddeps  :
    - pkgconfig(libpng)
    - pkgconfig(Qt5Script)
    - extra-cmake-modules
    - kcoreaddons-devel
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - kwindowsystem-devel
    - kxmlgui-devel
    - libksane-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/doc