name       : skanlite
version    : 23.04.3
release    : 21
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.3/src/skanlite-23.04.3.tar.xz : f2b10ad9af654ac9ffc4d2ec6cbe0a113e48f7c48505e9a1ae0cf56d421dd73c
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : Image Scanning Application for KDE
description: |
    Skanlite is a simple image scanning application that does nothing more than scan and save images, based on the KSane backend.
builddeps  :
    - pkgconfig(Qt5Script)
    - kdoctools-devel
    - kio-devel
    - ksanecore-devel
    - libksane-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/doc
