name       : skanlite
version    : 23.04.1
release    : 19
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.1/src/skanlite-23.04.1.tar.xz : e62b75d4733ceffc61e0f9c74b2cbd3cb4669c0952f00b3166cc6d31dd46cf6e
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : Image Scanning Application for KDE
description: |
    Skanlite is a simple image scanning application that does nothing more than scan and save images, based on the KSane backend.
builddeps  :
    - pkgconfig(Qt5Script)
    - kdoctools-devel
    - kio-devel
    - ksanecore-devel
    - libksane-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/doc
