name       : skanlite
version    : 21.08.2
release    : 7
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.2/src/skanlite-21.08.2.tar.xz : ada63f4a7561eb2c4d70d21314850dd955f1f1fa0fdd53d6da64887ee45999ff
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : Image Scanning Application for KDE
description: |
    Skanlite is a simple image scanning application that does nothing more than scan and save images, based on the KSane backend.
builddeps  :
    - pkgconfig(Qt5Script)
    - kdoctools-devel
    - kio-devel
    - libksane-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/doc
