name       : skanlite
version    : 21.12.1
release    : 10
source     :
    - https://cdn.download.kde.org/stable/release-service/21.12.1/src/skanlite-21.12.1.tar.xz : 1d1d993195e6bca7bd02ab5d1018851b93cdb38273a54859b9e976802ae3a368
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : Image Scanning Application for KDE
description: |
    Skanlite is a simple image scanning application that does nothing more than scan and save images, based on the KSane backend.
builddeps  :
    - pkgconfig(Qt5Script)
    - kdoctools-devel
    - kio-devel
    - libksane-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/doc
