name       : skanlite
version    : 22.04.1
release    : 13
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.1/src/skanlite-22.04.1.tar.xz : 69f7fe0850459c5f81767b4d3ba4d60ffcb3e495d9a2eaf1461bb95b56f013c8
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : Image Scanning Application for KDE
description: |
    Skanlite is a simple image scanning application that does nothing more than scan and save images, based on the KSane backend.
builddeps  :
    - pkgconfig(Qt5Script)
    - kdoctools-devel
    - kio-devel
    - libksane-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/doc
